version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: always
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    env_file:
      - .env
    command:
      "http --domain=$NGROK_DOMAIN ollama:11434"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"

volumes:
  ollama: